# Generated by Django 6.0.4 on 2026-05-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=50)),
                ('threshold', models.FloatField()),
                ('condition', models.CharField(default='>', max_length=10)),
                ('severity', models.CharField(default='CRITICAL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_adaptive_factor', models.FloatField(default=0.0)),
                ('network_delay_sec', models.FloatField(default=0.0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('cpu_load', models.FloatField(default=0.0)),
                ('adaptive_mode', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_state',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.alertrule')),
            ],
        ),
    ]
