# Generated by Django 6.0.4 on 2026-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
