# Generated by Django 6.0.4 on 2026-05-05 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_officer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='pno',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(default='NORMAL', max_length=20)),
                ('delivered', models.BooleanField(default=False)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
            },
        ),
    ]
