# Generated by Django 6.0.4 on 2026-05-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_officer_fcm_token_officer_role_alter_officer_pno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='blind_approval_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='co_decision_accuracy',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='officer',
            name='company',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='device_trust_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='officer',
            name='is_untrusted_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_integrity_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='platoon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officer',
            name='review_count_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='reviewer_bias_level',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='officer',
            name='reviewer_trust_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[('MANAGEMENT', 'Management/Admin'), ('CO', 'Commandant'), ('DC', 'Deputy Commandant'), ('AC', 'Assistant Commandant'), ('QM', 'Quarter Master'), ('CC', 'Company Commander'), ('SM', 'Subedar Major'), ('PC', 'Platoon Commander'), ('HC', 'Head Constable'), ('CONSTABLE', 'Constable')], default='CONSTABLE', max_length=20),
        ),
    ]
