# Generated by Django 6.0.4 on 2026-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_officer_blind_approval_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_pilot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('PILOT', 'Pilot'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
