# Generated by Django 6.0.4 on 2026-05-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_officer_is_pilot_alter_officer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='is_pilot',
        ),
    ]
