# Generated by Django 6.0.4 on 2026-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_officer_is_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='challenge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='daily_otp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='device_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_otp_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_request_at',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_risk_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='permanent_suspicion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officer',
            name='security_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='officer',
            name='silent_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='otprecord',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
