# Generated by Django 6.0.4 on 2026-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_officer_challenge_count_officer_daily_otp_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='device_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_id_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='integrity_level',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='route',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
