# Generated by Django 6.0.4 on 2026-05-06 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_auditlog_device_id_auditlog_device_id_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotOverrideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_field', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending CO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('integrity_state', models.CharField(default='UNKNOWN', max_length=50)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('commanding_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_ratified', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pilot_override_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
