# Generated by Django 6.0.4 on 2026-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_pilotoverriderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='approval_correlation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='approved_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='approved_device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='approved_integrity_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='escalation_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pilotoverriderequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
