# Generated by Django 6.0.4 on 2026-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_pilotoverriderequest_approval_correlation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='app_channel',
            field=models.CharField(choices=[('PILOT', 'Pilot'), ('STABLE', 'Stable')], default='STABLE', max_length=10),
        ),
    ]
