# Generated by Django 6.0.4 on 2026-05-06 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_officer_app_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='RankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(help_text='Higher is more senior (e.g., CO=10, Constable=1)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rank_master',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unit_master',
            },
        ),
        migrations.RemoveField(
            model_name='devicechangerequest',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='pilotoverriderequest',
            name='commanding_officer',
        ),
        migrations.RemoveField(
            model_name='pilotoverriderequest',
            name='pilot',
        ),
        migrations.RemoveField(
            model_name='pilotoverriderequest',
            name='target_user',
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='consent_accepted_at',
            new_name='deactivated_at',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='blocked_reason',
            new_name='deactivated_reason',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='device_registered_at',
            new_name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='app_channel',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='blind_approval_count',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='challenge_count',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='co_decision_accuracy',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='daily_otp_count',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='device_secret',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='device_trust_score',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='is_untrusted_device',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_approval_at',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_integrity_check_at',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_otp_at',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_request_at',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_risk_update',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='locked_until',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='permanent_suspicion',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='platoon',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='reporting_to',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='review_count_total',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='reviewer_bias_level',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='reviewer_trust_score',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='security_risk_score',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='silent_risk_score',
        ),
        migrations.RemoveField(
            model_name='otprecord',
            name='attempts',
        ),
        migrations.AddField(
            model_name='officer',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='pno',
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('COMMANDING_OFFICER', 'Commanding Officer'), ('PILOT', 'Pilot'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='OfficerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.TextField(blank=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_otp_at', models.DateTimeField(blank=True, null=True)),
                ('daily_otp_count', models.IntegerField(default=0)),
                ('permanent_suspicion', models.IntegerField(default=0)),
                ('security_risk_score', models.FloatField(default=0.0)),
                ('silent_risk_score', models.FloatField(default=0.0)),
                ('last_request_at', models.BigIntegerField(default=0)),
                ('device_secret', models.CharField(blank=True, max_length=128)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'officer_credentials',
            },
        ),
        migrations.CreateModel(
            name='OfficerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('android_version', models.CharField(blank=True, max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('LOST', 'Lost'), ('COMPROMISED', 'Compromised'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('integrity_level', models.CharField(default='UNKNOWN', max_length=50)),
                ('trust_score', models.FloatField(default=100.0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('last_integrity_check_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'officer_devices',
                'unique_together': {('officer', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True)),
                ('proposed_value', models.TextField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending CO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('integrity_state', models.CharField(default='UNKNOWN', max_length=50)),
                ('commanding_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_ratified', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_initiated', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides_target', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'override_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatoonMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platoons', to='auth_app.companymaster')),
            ],
            options={
                'db_table': 'platoon_master',
                'unique_together': {('company', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_status', models.CharField(choices=[('ACTIVE', 'On Duty'), ('LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired/Departed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.companymaster')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('reporting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates_profile', to=settings.AUTH_USER_MODEL)),
                ('platoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.platoonmaster')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.rankmaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'officer_profiles',
            },
        ),
        migrations.CreateModel(
            name='OfficerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=9)),
                ('action', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security Alert')], default='INFO', max_length=10)),
                ('related_incident_id', models.UUIDField(blank=True, null=True)),
                ('route', models.CharField(default='unknown', max_length=255)),
                ('result', models.CharField(default='SUCCESS', max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('device_id_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'officer_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.JSONField(null=True)),
                ('new_value', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_received', to=settings.AUTH_USER_MODEL)),
                ('override_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.overriderequest')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'draft_changes',
            },
        ),
        migrations.AddField(
            model_name='companymaster',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='auth_app.unitmaster'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='auth_app.unitmaster'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DeviceChangeRequest',
        ),
        migrations.DeleteModel(
            name='PilotOverrideRequest',
        ),
        migrations.AlterUniqueTogether(
            name='companymaster',
            unique_together={('unit', 'code')},
        ),
    ]
