# Generated by Django 6.0.4 on 2026-05-07 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_companymaster_rankmaster_unitmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversarialSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('affected_actors', models.JSONField()),
                ('confidence_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adversarial_signals',
            },
        ),
        migrations.CreateModel(
            name='ConstitutionalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_reference', models.CharField(max_length=50, unique=True)),
                ('classification', models.CharField(choices=[('HARD_INVARIANT', 'Executable System Law'), ('ENFORCED_POLICY', 'Standard Operational Policy'), ('OPERATIONAL_GUIDANCE', 'Recommended Best Practice'), ('PHILOSOPHICAL_PRINCIPLE', 'Core Mission Value')], max_length=30)),
                ('intent_description', models.TextField()),
                ('is_evolutionary', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'constitutional_articles',
            },
        ),
        migrations.CreateModel(
            name='ConstitutionalEnforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_reference', models.CharField(max_length=50)),
                ('invariant_key', models.CharField(max_length=100)),
                ('enforcement_status', models.CharField(default='ACTIVE', max_length=20)),
                ('audit_frequency', models.IntegerField(default=3600)),
                ('last_verified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constitutional_enforcement',
            },
        ),
        migrations.CreateModel(
            name='DeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.UUIDField(unique=True)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('error_log', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dead_events',
            },
        ),
        migrations.CreateModel(
            name='DecisionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inference_type', models.CharField(max_length=100)),
                ('triggering_signals', models.JSONField()),
                ('signal_weights', models.JSONField()),
                ('remediation_chosen', models.CharField(max_length=100)),
                ('rejected_alternatives', models.JSONField(default=list)),
                ('confidence_score', models.IntegerField()),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'decision_traces',
            },
        ),
        migrations.CreateModel(
            name='DistributedLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'distributed_locks',
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('type', models.CharField(max_length=50)),
                ('actor_id', models.IntegerField(null=True)),
                ('unit_id', models.IntegerField()),
                ('payload', models.JSONField()),
                ('trace_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('sequence', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_outbox',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_key', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_analysis', models.JSONField()),
                ('approved_by', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evolution_logs',
            },
        ),
        migrations.CreateModel(
            name='ExplainabilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_key', models.CharField(choices=[('TACTICAL', 'Field User (Action Only)'), ('OPERATIONAL', 'Pilot (Situational Context)'), ('GOVERNANCE', 'CO (Policy Impact)'), ('FORENSIC', 'Auditor (Lineage & Traces)'), ('ARCHITECTURAL', 'Engineer (Invariants & State)')], max_length=20, unique=True)),
                ('visibility_mask', models.JSONField()),
            ],
            options={
                'db_table': 'explainability_levels',
            },
        ),
        migrations.CreateModel(
            name='FailureSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_key', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('impact_scope', models.JSONField()),
                ('status', models.CharField(default='PLANNED', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('recovered_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'failure_simulations',
            },
        ),
        migrations.CreateModel(
            name='GovernanceConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_key', models.CharField(max_length=100)),
                ('current_value', models.FloatField()),
                ('ceiling_threshold', models.FloatField()),
                ('is_violated', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'governance_constraints',
            },
        ),
        migrations.CreateModel(
            name='HealingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Comparing Revisions'), ('ANALYZING', 'Detecting Divergence'), ('REPLAYING', 'Applying Missing Events'), ('RECONCILING', 'Merging Offline Drafts'), ('COMPLETED', 'Divergence Resolved'), ('FAILED', 'Manual Intervention Required')], default='STARTED', max_length=20)),
                ('start_revision', models.BigIntegerField()),
                ('end_revision', models.BigIntegerField()),
                ('divergence_log', models.JSONField(default=list)),
                ('reconciled_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'healing_sessions',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_records',
            },
        ),
        migrations.CreateModel(
            name='InvariantViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invariant_key', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technical_trace', models.JSONField()),
                ('severity', models.CharField(default='CRITICAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invariant_violations',
            },
        ),
        migrations.CreateModel(
            name='PartitionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('HEALTHY', 'Fully Connected'), ('SUSPECTED', 'Intermittent Signals'), ('DEGRADED', 'High Packet Loss/Skew'), ('PARTITIONED', 'Confirmed Isolation'), ('RECOVERING', 'Restoring Connectivity')], default='HEALTHY', max_length=20)),
                ('confidence_score', models.IntegerField(default=100)),
                ('signals', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partition_states',
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'platform_metrics',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('findings', models.JSONField()),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy_audits',
            },
        ),
        migrations.CreateModel(
            name='ReadFenceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pinned_revision', models.BigIntegerField()),
                ('reader_type', models.CharField(choices=[('ANDROID_SYNC', 'Mobile Device Sync'), ('COCKPIT', 'Operational Dashboard'), ('HYDRATION', 'Realtime Hydration'), ('GOVERNANCE', 'Approval Engine')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'read_fence_sessions',
            },
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('subsystem', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
                ('status', models.CharField(default='STARTED', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remediation_actions',
            },
        ),
        migrations.CreateModel(
            name='RemediationBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(max_length=50, unique=True)),
                ('max_actions_per_hour', models.IntegerField(default=10)),
                ('cooldown_seconds', models.IntegerField(default=300)),
                ('current_hourly_count', models.IntegerField(default=0)),
                ('last_action_at', models.DateTimeField(null=True)),
                ('is_halted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'remediation_budgets',
            },
        ),
        migrations.CreateModel(
            name='SemanticDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, unique=True)),
                ('original_meaning', models.TextField()),
                ('current_reinterpretation', models.TextField(blank=True)),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
                ('conflict_detected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'semantic_drifts',
            },
        ),
        migrations.CreateModel(
            name='SimplificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('target_subsystem', models.CharField(max_length=50)),
                ('complexity_delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simplification_actions',
            },
        ),
        migrations.CreateModel(
            name='SnapshotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREPARING', 'Freezing Subsystems'), ('DRAINING', 'Draining Outbox/Queues'), ('CAPTURING', 'Recording State'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed/Timed Out')], default='PREPARING', max_length=20)),
                ('snapshot_revision', models.BigIntegerField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_subsystems', models.JSONField(default=list)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'snapshot_sessions',
            },
        ),
        migrations.CreateModel(
            name='TrustDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('NETWORK', 'Communication Stability'), ('DEVICE', 'Hardware Integrity'), ('REPLAY', 'Temporal Lineage'), ('OPERATOR', 'Human Authority'), ('EVIDENCE', 'Chain-of-Custody')], max_length=20, unique=True)),
                ('trust_score', models.IntegerField(default=100)),
                ('last_degradation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trust_domains',
            },
        ),
        migrations.CreateModel(
            name='TrustRecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20)),
                ('start_score', models.IntegerField()),
                ('end_score', models.IntegerField()),
                ('recovery_reason', models.TextField()),
                ('trace_id', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trust_recovery_logs',
            },
        ),
        migrations.AlterModelOptions(
            name='draftchange',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='draftchange',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftchange',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draftchange',
            name='expected_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftchange',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftchange',
            name='rejecter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officer',
            name='revision',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='officer',
            name='session_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='revision',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='draftchange',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONFLICTED', 'Conflicted'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('SILENT', 'Silent Sync'), ('INFO', 'Passive Info'), ('IMPORTANT', 'Important Notice'), ('URGENT', 'Urgent Alert'), ('CRITICAL', 'Mission Critical Broadcast')], default='INFO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_reference', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('recovery_ratified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_exceptions',
            },
        ),
        migrations.CreateModel(
            name='ExceptionDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_plan', models.TextField()),
                ('review_deadline', models.DateTimeField()),
                ('impact_score', models.IntegerField()),
                ('burden_score', models.IntegerField()),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(null=True)),
                ('exception', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='auth_app.emergencyexception')),
            ],
            options={
                'db_table': 'exception_debts',
            },
        ),
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='field_data/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('EVIDENCE', 'Forensic Evidence'), ('DOCUMENT', 'Official Document'), ('MAP', 'Operational Map'), ('INTEL', 'Intelligence Report')], default='DOCUMENT', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'field_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ARCHIVED', 'Archived')], default='REPORTED', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_manifest', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('linked_devices', models.ManyToManyField(blank=True, related_name='linked_incidents', to='auth_app.officerdevice')),
                ('linked_officers', models.ManyToManyField(blank=True, related_name='linked_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Incident Created'), ('STATUS_CHANGED', 'Status Changed'), ('SEVERITY_CHANGED', 'Severity Changed'), ('EVIDENCE_ADDED', 'Evidence Added'), ('OFFICER_LINKED', 'Officer Linked'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='auth_app.incident')),
            ],
            options={
                'db_table': 'incident_timeline',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OperationalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('sequence', models.BigIntegerField(db_index=True, default=0)),
                ('schema_version', models.IntegerField(default=1)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_triggered', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'operational_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('SILENT', 'Silent Sync'), ('INFO', 'Passive Info'), ('IMPORTANT', 'Realtime In-App'), ('URGENT', 'Immediate Notification'), ('CRITICAL', 'Broadcast + Siren + Push')], default='INFO', max_length=20)),
                ('channel', models.CharField(choices=[('WEBSOCKET', 'WebSocket Gateway'), ('FCM_PUSH', 'FCM Push Notification'), ('SMS', 'Emergency SMS')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered/Acked'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='QUEUED', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='auth_app.operationalevent')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalFSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('HEALTHY', 'Stable Operation'), ('DEGRADED', 'Performance Pressure'), ('PARTITIONED', 'Network Fragmentation'), ('HEALING', 'Reconciliation Phase'), ('RECOVERY', 'Disaster Restoration'), ('LOCKDOWN', 'Security Restriction'), ('FORENSIC', 'Audit Replay Mode')], default='HEALTHY', max_length=20)),
                ('previous_state', models.CharField(choices=[('HEALTHY', 'Stable Operation'), ('DEGRADED', 'Performance Pressure'), ('PARTITIONED', 'Network Fragmentation'), ('HEALING', 'Reconciliation Phase'), ('RECOVERY', 'Disaster Restoration'), ('LOCKDOWN', 'Security Restriction'), ('FORENSIC', 'Audit Replay Mode')], max_length=20, null=True)),
                ('transition_reason', models.TextField()),
                ('trace_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_fsm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtaUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_code', models.IntegerField(unique=True)),
                ('version_name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='ota_updates/')),
                ('sha256', models.CharField(max_length=64)),
                ('changelog', models.TextField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('STAGED', 'Staged Rollout'), ('PRODUCTION', 'Full Production'), ('DEPRECATED', 'Deprecated'), ('REVOKED', 'Revoked/Emergency Rollback')], default='STAGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('target_units', models.ManyToManyField(blank=True, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'ota_updates',
                'ordering': ['-version_code'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(choices=[('NORMAL', 'Standard Operation'), ('INCIDENT', 'Elevated Awareness'), ('DEGRADED', 'Low Bandwidth/Capacity'), ('LOCKDOWN', 'Restricted Mutation'), ('RECOVERY', 'Event Replay Only')], default='NORMAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_modes',
            },
        ),
        migrations.CreateModel(
            name='RealtimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('socket_id', models.CharField(max_length=100, unique=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('system_mode', models.CharField(default='NORMAL', max_length=20)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'realtime_sessions',
            },
        ),
        migrations.CreateModel(
            name='OutcomeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_metric_snapshot', models.JSONField()),
                ('post_metric_snapshot', models.JSONField(null=True)),
                ('effectiveness', models.CharField(default='UNKNOWN', max_length=20)),
                ('verified_at', models.DateTimeField(null=True)),
                ('remediation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='auth_app.remediationaction')),
            ],
            options={
                'db_table': 'outcome_verifications',
            },
        ),
        migrations.CreateModel(
            name='SnapshotAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(choices=[('OFFICERS', 'Officer Base State'), ('INCIDENTS', 'Incident Ledger'), ('GOVERNANCE', 'Governance State Machine'), ('DEVICES', 'Device Binding Map'), ('AUDIT', 'Audit Lineage Header')], max_length=50)),
                ('revision', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('is_compressed', models.BooleanField(default=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snapshot_aggregates',
                'ordering': ['-revision'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='training_docs/')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.unitmaster')),
            ],
            options={
                'db_table': 'training_modules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acked_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='auth_app.broadcast')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_acknowledgments',
                'unique_together': {('broadcast', 'officer')},
            },
        ),
        migrations.CreateModel(
            name='ComprehensionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=100)),
                ('verification_token', models.CharField(max_length=100)),
                ('understanding_score', models.IntegerField()),
                ('implications_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comprehension_verifications',
                'indexes': [models.Index(fields=['created_at'], name='comprehensi_created_f7a048_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='auth_app.trainingmodule')),
            ],
            options={
                'db_table': 'training_acknowledgments',
                'unique_together': {('module', 'officer')},
            },
        ),
    ]
