# Generated by Django 6.0.4 on 2026-05-07 07:01

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_adversarialsignal_constitutionalarticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('subsystem', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
                ('status', models.CharField(db_index=True, default='STARTED', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recovery_actions',
            },
        ),
        migrations.RemoveIndex(
            model_name='comprehensionverification',
            name='comprehensi_created_f7a048_idx',
        ),
        migrations.DeleteModel(
            name='ConstitutionalArticle',
        ),
        migrations.DeleteModel(
            name='ConstitutionalEnforcement',
        ),
        migrations.DeleteModel(
            name='DecisionTrace',
        ),
        migrations.RemoveField(
            model_name='emergencyexception',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='exceptiondebt',
            name='exception',
        ),
        migrations.DeleteModel(
            name='EvolutionLog',
        ),
        migrations.DeleteModel(
            name='ExplainabilityLevel',
        ),
        migrations.DeleteModel(
            name='FailureSimulation',
        ),
        migrations.DeleteModel(
            name='GovernanceConstraint',
        ),
        migrations.DeleteModel(
            name='HealingSession',
        ),
        migrations.RemoveField(
            model_name='outcomeverification',
            name='remediation',
        ),
        migrations.DeleteModel(
            name='PartitionState',
        ),
        migrations.DeleteModel(
            name='PlatformMetrics',
        ),
        migrations.DeleteModel(
            name='PolicyAudit',
        ),
        migrations.DeleteModel(
            name='ReadFenceSession',
        ),
        migrations.DeleteModel(
            name='RemediationBudget',
        ),
        migrations.DeleteModel(
            name='SemanticDrift',
        ),
        migrations.DeleteModel(
            name='SimplificationAction',
        ),
        migrations.RemoveField(
            model_name='snapshotaggregate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SnapshotSession',
        ),
        migrations.DeleteModel(
            name='TrustDomain',
        ),
        migrations.DeleteModel(
            name='TrustRecoveryLog',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='targeted_officers',
            field=models.ManyToManyField(blank=True, related_name='targeted_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distributedlock',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='draftchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='draftchange',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('APPLYING', 'Applying'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONFLICTED', 'Conflicted'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventoutbox',
            name='sequence',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='eventoutbox',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='officeractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='officeractivity',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security Alert')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='operationalevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='operationalfsm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='otaupdate',
            name='status',
            field=models.CharField(choices=[('STAGED', 'Staged Rollout'), ('PRODUCTION', 'Full Production'), ('DEPRECATED', 'Deprecated'), ('REVOKED', 'Revoked/Emergency Rollback')], db_index=True, default='STAGED', max_length=20),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending CO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='draftchange',
            index=models.Index(fields=['status', 'created_at'], name='draft_chang_status_74f62b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['status', 'created_at'], name='event_outbo_status_bd9755_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutbox',
            index=models.Index(fields=['sequence'], name='event_outbo_sequenc_782afd_idx'),
        ),
        migrations.AddIndex(
            model_name='officeractivity',
            index=models.Index(fields=['created_at'], name='officer_act_created_0c0dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='officeractivity',
            index=models.Index(fields=['severity', 'created_at'], name='officer_act_severit_b7ab0c_idx'),
        ),
        migrations.AddIndex(
            model_name='officeractivity',
            index=models.Index(fields=['pno'], name='officer_act_pno_272d76_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['created_at'], name='operational_created_e0ab51_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['correlation_id'], name='operational_correla_4a95eb_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalevent',
            index=models.Index(fields=['sequence'], name='operational_sequenc_b1105f_idx'),
        ),
        migrations.AddIndex(
            model_name='overriderequest',
            index=models.Index(fields=['status', 'created_at'], name='override_re_status_fb7db8_idx'),
        ),
        migrations.AddIndex(
            model_name='recoveryaction',
            index=models.Index(fields=['status', 'started_at'], name='recovery_ac_status_673043_idx'),
        ),
        migrations.RemoveField(
            model_name='comprehensionverification',
            name='officer',
        ),
        migrations.DeleteModel(
            name='EmergencyException',
        ),
        migrations.DeleteModel(
            name='ExceptionDebt',
        ),
        migrations.DeleteModel(
            name='OutcomeVerification',
        ),
        migrations.DeleteModel(
            name='RemediationAction',
        ),
        migrations.DeleteModel(
            name='SnapshotAggregate',
        ),
        migrations.DeleteModel(
            name='ComprehensionVerification',
        ),
    ]
