# Generated by Django 6.0.4 on 2026-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_recoveryaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmaster',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('RTC', 'Recruit Training Center'), ('BATTALION', 'Battalion / Company Units')], default='BATTALION', max_length=10),
        ),
    ]
