# Generated by Django 6.0.4 on 2026-05-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_unitmaster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='officercredential',
            name='last_password_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
