# Generated by Django 4.2.11 on 2026-05-21 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_officer_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='broadcast_type',
            field=models.CharField(default='TEXT', max_length=50),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PILOT', 'Pilot'), ('USER', 'User')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='overriderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending ADMIN Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BroadcastDispatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('broadcast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_job', to='auth_app.broadcast')),
            ],
            options={
                'db_table': 'broadcast_dispatch_jobs',
            },
        ),
        migrations.CreateModel(
            name='BroadcastAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('remote_url', models.URLField(max_length=1000)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='auth_app.broadcast')),
            ],
            options={
                'db_table': 'broadcast_attachments',
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('pno', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='QUEUED', max_length=50)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='auth_app.broadcast')),
            ],
            options={
                'db_table': 'broadcast_recipients',
                'unique_together': {('broadcast', 'user_id')},
            },
        ),
    ]
