# Generated by Django 6.0.4 on 2026-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='s3_key',
        ),
        migrations.AddField(
            model_name='training',
            name='video_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
