# Generated by Django 6.0.4 on 2026-05-06 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.IntegerField(unique=True)),
                ('version_name', models.CharField(max_length=50)),
                ('apk_file', models.FileField(upload_to='builds/')),
                ('apk_hash_sha256', models.CharField(help_text='SHA-256 hash of the APK for integrity verification.', max_length=64)),
                ('channel', models.CharField(choices=[('PILOT', 'Pilot (Internal/Unstable)'), ('STABLE', 'Stable (Officers/Production)'), ('EMERGENCY', 'Emergency (Hotfix)')], default='PILOT', max_length=20)),
                ('is_forced', models.BooleanField(default=False, help_text='If true, user cannot dismiss the update prompt.')),
                ('min_supported_version', models.IntegerField(default=1, help_text='Versions below this will be forced to update.')),
                ('release_notes', models.TextField(blank=True)),
                ('is_rollback_allowed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_releases', to=settings.AUTH_USER_MODEL)),
                ('previous_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_releases', to='admin_panel.apprelease')),
            ],
            options={
                'db_table': 'app_releases',
                'ordering': ['-version_code'],
            },
        ),
    ]
