# Generated by Django 6.0.4 on 2026-05-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry date (useful for Emergency hotfixes).', null=True),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='rollout_percentage',
            field=models.IntegerField(default=100, help_text='Percentage of users (0-100) who will receive this update.'),
        ),
    ]
