# Generated by Django 6.0.4 on 2026-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_apprelease_expires_at_apprelease_rollout_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='is_critical_override',
            field=models.BooleanField(default=False, help_text='If true, staged rollout percentage is ignored.'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='schema_version',
            field=models.IntegerField(default=1, help_text='Increment this if DB schema changes. Used for safe rollback detection.'),
        ),
    ]
