# Generated by Django 6.0.4 on 2026-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_apprelease_is_critical_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='approval_reason',
            field=models.TextField(blank=True, help_text='Mandatory for Critical/Emergency releases.'),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='min_supported_schema',
            field=models.IntegerField(default=1, help_text='Lowest schema version this app version can handle (for rollback safety).'),
        ),
        migrations.AlterField(
            model_name='apprelease',
            name='schema_version',
            field=models.IntegerField(default=1, help_text='Current schema version of this release.'),
        ),
    ]
