# Generated by Django 6.0.4 on 2026-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_apprelease_approval_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprelease',
            name='blast_radius',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='incident_id',
            field=models.CharField(blank=True, help_text='Link to internal incident tracker.', max_length=50),
        ),
        migrations.AddField(
            model_name='apprelease',
            name='release_category',
            field=models.CharField(choices=[('SECURITY', 'Security Patch'), ('HOTFIX', 'Bug Hotfix'), ('ROLLBACK', 'Release Rollback'), ('PLANNED', 'Planned Feature Update')], default='PLANNED', max_length=20),
        ),
    ]
