# Generated by Django 6.0.4 on 2026-05-04 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('grade', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('WARNING', 'Warning'), ('FLAGGED', 'Flagged')], default='EXCELLENT', max_length=10)),
                ('requires_review', models.BooleanField(default=False)),
                ('event_summary', models.JSONField(default=dict)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discipline_scores',
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('SEEK_ATTEMPT', 'Video Seek Attempt'), ('APP_BACKGROUND', 'App Backgrounded During Video'), ('APP_FOREGROUND', 'App Resumed'), ('QUIZ_FAST_ANSWER', 'Quiz Answer Too Fast'), ('QUIZ_ATTEMPT', 'Quiz Attempt'), ('TRAINING_COMPLETE', 'Training Completed'), ('DEVICE_MISMATCH', 'Device Mismatch'), ('HEARTBEAT_GAP', 'Heartbeat Gap Detected'), ('POSITION_STUCK', 'Video Position Not Advancing'), ('QUIZ_TOO_FAST', 'Quiz Completed Too Fast')], max_length=30)),
                ('timestamp_ms', models.BigIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'behavior_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['officer', 'event_type'], name='behavior_ev_officer_74d295_idx'), models.Index(fields=['officer', 'received_at'], name='behavior_ev_officer_d96167_idx')],
            },
        ),
    ]
