# Generated by Django 6.0.4 on 2026-05-05 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('timestampMs', models.BigIntegerField(db_index=True)),
                ('level', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('remark', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_signature', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'character_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='anomaly_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='auto_action',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='is_anomaly_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['event_type'], name='behavior_ev_event_t_cb6ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='behaviorevent',
            index=models.Index(fields=['timestamp_ms'], name='behavior_ev_timesta_991dde_idx'),
        ),
    ]
