# Generated by Django 6.0.4 on 2026-05-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_characterentry_disciplinescore_anomaly_reasons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(default='NORMAL', max_length=20)),
                ('avg_anomaly_score', models.FloatField(default=0)),
                ('common_patterns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'behavioral_clusters',
            },
        ),
        migrations.CreateModel(
            name='PilotMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_decisions', models.IntegerField(default=0)),
                ('total_overrides', models.IntegerField(default=0)),
                ('total_rollbacks', models.IntegerField(default=0)),
                ('total_defers', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('system_accuracy', models.FloatField(default=0.0)),
                ('alert_count', models.IntegerField(default=0)),
                ('avg_review_time_sec', models.IntegerField(default=0)),
                ('blind_approvals', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pilot_metrics',
            },
        ),
        migrations.CreateModel(
            name='RemoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remote_configs',
            },
        ),
        migrations.RemoveField(
            model_name='disciplinescore',
            name='auto_action',
        ),
        migrations.RemoveField(
            model_name='disciplinescore',
            name='is_anomaly_high_risk',
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='accumulated_suspicion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='anchor_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='anchor_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='anomaly_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='cluster_bias_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='cumulative_drift',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='decision_audit_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='enforcement_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='enforcement_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='good_behavior_streak_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='influence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='is_command_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='is_experimental_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_arbitrated_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_decision_explanation',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_decision_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_rollback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_safe_mode_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='last_violation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='learning_freeze_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='learning_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='model_weights_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='momentum_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='monitoring_mode',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='monitoring_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='override_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='pending_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='performance_msg',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='performance_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='predicted_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='reputation_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='resolution_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='risk_level',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SUSPICIOUS', 'Suspicious'), ('HIGH_RISK', 'High Risk')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='safe_mode_trigger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='system_accuracy_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='system_health_index',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='trajectory_status',
            field=models.CharField(default='STABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='disciplinescore',
            name='trust_level',
            field=models.CharField(choices=[('TRUSTED', 'Trusted (High Integrity)'), ('NORMAL', 'Normal'), ('WATCHLIST', 'Watchlist (Risky)'), ('RESTRICTED', 'Restricted (High Risk)')], default='NORMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='CommandSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('REVIEW_REQUIRED', 'Review Required'), ('WARNING', 'Issue Warning'), ('RESTRICTION', 'Temporary Restriction'), ('OBSERVATION', 'Extended Observation'), ('NO_ACTION', 'No Action Needed')], max_length=50)),
                ('score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_processed', models.BooleanField(default=False)),
                ('admin_action', models.CharField(blank=True, max_length=50, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'command_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('pre_score', models.FloatField()),
                ('post_score', models.FloatField(blank=True, null=True)),
                ('effectiveness_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audited_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('CRITICAL_ACK_DELAY', 'Critical Alert ACK Delay'), ('DEVICE_TAMPER', 'Device/Environment Tamper'), ('TRAINING_SKIP', 'Training Circumvention Attempt')], max_length=30)),
                ('severity', models.CharField(default='NORMAL', max_length=10)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('AUTO_DELAY', 'Automatic Delay Penalty'), ('AUTO_ACK', 'Automatic ACK Failure Penalty'), ('MANUAL', 'Manual Administrative Penalty')], max_length=20)),
                ('score_deduction', models.IntegerField()),
                ('reason', models.TextField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='behavior.violation')),
            ],
            options={
                'db_table': 'penalty_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_score', models.FloatField()),
                ('risk_status', models.CharField(max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('window_end', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'violation_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_contribution', models.FloatField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='behavior.behavioralcluster')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cluster_memberships',
                'unique_together': {('cluster', 'officer')},
            },
        ),
        migrations.CreateModel(
            name='SimilarityEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('common_features', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'similarity_edges',
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
