# Generated by Django 6.0.4 on 2026-05-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0003_behavioralcluster_pilotmetric_remoteconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerReliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliability_score', models.FloatField(default=1.0)),
                ('bias_flag', models.BooleanField(default=False)),
                ('deviation_count', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reliability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewer_reliability',
            },
        ),
    ]
